"""YOLOv8-Seg training and validation helpers for binary eyewear segmentation."""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Any

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent
EXPECTED_CLASS_COUNT = 1
EXPECTED_CLASS_NAMES = {0: "eyewear"}


def validate_dataset_structure(dataset_root: str | Path) -> bool:
    """Validate the actual repository dataset layout used by data.yaml."""
    dataset_path = Path(dataset_root).resolve()
    images_dir = dataset_path / "images"
    labels_dir = dataset_path / "labels"

    if not images_dir.exists():
        logger.error("images/ directory not found in %s", dataset_path)
        return False
    if not labels_dir.exists():
        logger.error("labels/ directory not found in %s", dataset_path)
        return False

    ok = True
    for split in ("train", "val"):
        image_dir = images_dir / split
        label_dir = labels_dir / split

        if not image_dir.exists():
            logger.error("Missing image split: %s", image_dir)
            ok = False
            continue
        if not label_dir.exists():
            logger.error("Missing label split: %s", label_dir)
            ok = False
            continue

        image_files = [p for p in image_dir.iterdir() if p.is_file()]
        label_files = list(label_dir.glob("*.txt"))

        if not image_files:
            logger.error("%s has no images", image_dir)
            ok = False
        if not label_files:
            logger.error("%s has no YOLO labels", label_dir)
            ok = False

        logger.info(
            "%s: %d images, %d labels",
            split,
            len(image_files),
            len(label_files),
        )

    if ok:
        logger.info("Dataset structure validated: %s", dataset_path)
    return ok


def create_yolo_dataset_yaml(
    dataset_root: str | Path,
    output_path: str | Path = "data.yaml",
) -> Path:
    """Create a portable YAML whose path is relative to the YAML file."""
    dataset_path = Path(dataset_root).resolve()
    output = Path(output_path).resolve()

    relative_dataset = os.path.relpath(dataset_path, output.parent).replace("\\", "/")
    if relative_dataset == ".":
        yaml_path_value = "."
    else:
        yaml_path_value = f"./{relative_dataset}"

    yaml_content = f"""# YOLOv8-Seg — binary eyewear segmentation
# Generated by train_yolov8_seg.py. Paths are relative to this YAML.

path: {yaml_path_value}
train: images/train
val: images/val

nc: 1
names:
  0: eyewear
"""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(yaml_content, encoding="utf-8")
    logger.info("Created portable dataset YAML: %s", output)
    return output


def validate_model_contract(model_path: str | Path) -> dict[int, str]:
    """Load a YOLO checkpoint and verify the project 1-class contract."""
    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise RuntimeError(
            "ultralytics is not installed. Run: pip install -r requirements.txt"
        ) from exc

    path = Path(model_path).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"YOLO model not found: {path}")

    model = YOLO(str(path))
    raw_names = getattr(getattr(model, "model", None), "names", {})
    if isinstance(raw_names, dict):
        names = {int(k): str(v) for k, v in raw_names.items()}
    elif isinstance(raw_names, (list, tuple)):
        names = {i: str(v) for i, v in enumerate(raw_names)}
    else:
        names = {}

    if len(names) != EXPECTED_CLASS_COUNT or names != EXPECTED_CLASS_NAMES:
        raise RuntimeError(
            "YOLO model contract violation: "
            f"{path} exposes {len(names)} classes {names!r}; "
            f"expected {EXPECTED_CLASS_NAMES!r}."
        )

    logger.info("YOLO model contract OK: %s -> %s", path, names)
    return names


def train_yolov8_seg(
    dataset_yaml: str,
    model_name: str = "yolov8n-seg",
    epochs: int = 50,
    img_size: int = 640,
    batch_size: int = 16,
    device: str = "0",
    project_dir: str = "./runs/segment",
    name: str = "eyewear_seg",
    patience: int = 10,
    resume: bool = False,
) -> dict[str, Any]:
    try:
        from ultralytics import YOLO
    except ImportError:
        logger.error("ultralytics not installed. Run: pip install ultralytics")
        return {}

    logger.info("Loading base model: %s", model_name)
    model = YOLO(f"{model_name}.pt")

    logger.info(
        "Starting binary eyewear training (epochs=%d, batch=%d)",
        epochs,
        batch_size,
    )
    results = model.train(
        data=dataset_yaml,
        epochs=epochs,
        imgsz=img_size,
        batch=batch_size,
        device=device,
        project=project_dir,
        name=name,
        patience=patience,
        save=True,
        val=True,
        resume=resume,
        task="segment",
    )

    save_dir = getattr(results, "save_dir", Path(project_dir) / name)
    return {
        "timestamp": datetime.now().isoformat(),
        "model": model_name,
        "epochs": epochs,
        "batch_size": batch_size,
        "img_size": img_size,
        "results_dir": str(save_dir),
    }


def evaluate_model_on_dataset(
    model_path: str,
    dataset_yaml: str,
    img_size: int = 640,
    device: str = "0",
) -> dict[str, Any]:
    try:
        from ultralytics import YOLO
    except ImportError:
        logger.error("ultralytics not installed")
        return {}

    validate_model_contract(model_path)
    model = YOLO(model_path)
    metrics = model.val(data=dataset_yaml, imgsz=img_size, device=device)

    results = {
        "mAP50": float(metrics.box.map50) if hasattr(metrics, "box") else None,
        "mAP50_95": float(metrics.box.map) if hasattr(metrics, "box") else None,
        "segmentation_mAP50": float(metrics.seg.map50) if hasattr(metrics, "seg") else None,
        "segmentation_mAP50_95": float(metrics.seg.map) if hasattr(metrics, "seg") else None,
    }
    for key, value in results.items():
        if value is not None:
            logger.info("%s: %.4f", key, value)
    return results


def export_onnx(model_path: str, output_path: str = "model.onnx") -> str:
    try:
        from ultralytics import YOLO
    except ImportError:
        logger.error("ultralytics not installed")
        return ""

    validate_model_contract(model_path)
    model = YOLO(model_path)
    exported = model.export(format="onnx", imgsz=640)
    logger.info("Exported to %s", exported)
    return str(exported)


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="YOLOv8-Seg Training Pipeline")
    subparsers = parser.add_subparsers(dest="command")

    validate_parser = subparsers.add_parser("validate")
    validate_parser.add_argument(
        "--dataset-root",
        default=str(PROJECT_ROOT / "dataset"),
    )

    yaml_parser = subparsers.add_parser("create-yaml")
    yaml_parser.add_argument(
        "--dataset-root",
        default=str(PROJECT_ROOT / "dataset"),
    )
    yaml_parser.add_argument("--output", default="data.yaml")

    train_parser = subparsers.add_parser("train")
    train_parser.add_argument("--dataset-yaml", required=True)
    train_parser.add_argument("--model", default="yolov8n-seg")
    train_parser.add_argument("--epochs", type=int, default=50)
    train_parser.add_argument("--batch-size", type=int, default=16)
    train_parser.add_argument("--img-size", type=int, default=640)
    train_parser.add_argument("--device", default="0")
    train_parser.add_argument("--name", default="eyewear_seg")

    eval_parser = subparsers.add_parser("evaluate")
    eval_parser.add_argument("--model-path", required=True)
    eval_parser.add_argument("--dataset-yaml", required=True)
    eval_parser.add_argument("--device", default="0")

    export_parser = subparsers.add_parser("export")
    export_parser.add_argument("--model-path", required=True)
    export_parser.add_argument("--output", default="model.onnx")

    args = parser.parse_args()

    if args.command == "validate":
        valid = validate_dataset_structure(args.dataset_root)
        raise SystemExit(0 if valid else 1)

    elif args.command == "create-yaml":
        create_yolo_dataset_yaml(args.dataset_root, args.output)

    elif args.command == "train":
        yaml_path = Path(args.dataset_yaml).resolve()
        dataset_root = PROJECT_ROOT / "dataset"
        validate_dataset_structure(dataset_root)
        metadata = train_yolov8_seg(
            str(yaml_path),
            model_name=args.model,
            epochs=args.epochs,
            batch_size=args.batch_size,
            img_size=args.img_size,
            device=args.device,
            name=args.name,
        )
        print(json.dumps(metadata, indent=2))

    elif args.command == "evaluate":
        metrics = evaluate_model_on_dataset(
            args.model_path,
            args.dataset_yaml,
            device=args.device,
        )
        print(json.dumps(metrics, indent=2))

    elif args.command == "export":
        export_onnx(args.model_path, args.output)


if __name__ == "__main__":
    main()
